{{ if .Values.pachd.workerServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  # TODO if and .Values.pachd.storage.serviceAccountName eq .Values.pachd.storage.backend "GOOGLE"
  #annotations:
  #  iam.gke.io/gcp-service-account: "{{ .Values.pachd.storage.serviceAccountName }}"
  # end 
  labels:
    app: "" #TODO 
    suite: pachyderm
  name: {{ .Values.pachd.workerServiceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{ end }}