apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: pachyderm-storage
  name: pachyderm-storage
spec:
  replicas: 8
  selector:
    name: pachyderm-storage
  template:
    metadata:
      labels:
        name: pachyderm-storage
    spec:
      containers:
        - name: pachyderm-storage
          image: pachyderm/shard
          command: [ "-modulos", "8"]
          volumeMounts:
          - mountPath: /host
            name: host
          - mountPath: /var/lib/pfs/vol
            name: storage
          - mountPath: /var/run/docker.sock
            name: docker
          ports:
          - containerPort: 80
            name: port
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /
        name: host
      - hostPath:
          path: /var/lib/pfs/vol
        name: storage
      - hostPath:
          path: /var/run/docker.sock
        name: docker
