# Setup a Pachyderm CI machine with the Buildkite build agent running.
---
- hosts: tag_ci
  roles:
    - joshualund.golang
    - franklinkim.docker-compose
    - docker
    - { role: docker-gc, docker_gc_frequency: "daily" }
    - buildkite-agent
  tasks:
    - apt: pkg={{ item }} state=present
      with_items:
        - make
