# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  -
    id: "pachctl"
    dir: src/server/cmd/pachctl
    main: main.go
    binary: pachctl
    ldflags:
      #- -s -w -X src/client/version.AdditionalVersion={{.Env.VERSION_ADDITIONAL}} main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
      - -s -w -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    gcflags:
      - all=-trimpath={${PWD}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    #gobinary: "go1.13.8"
archives:
  - replacements:
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
scoop:
  url_template: "http://github.com/pachyderm/pachyderm/releases/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: pachyderm
    name: pachyderm
  commit_author:
    name: nitin
    email: nitin@pachyderm.com
  commit_msg_template: "Update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://www.pachyderm.com/"
  description: "Reproducible data science"
nfpms:
  -
    id: pachctl
    package_name: pachctl
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds: 
      - pachctl
    replacements:
      linux: 
      amd64: amd64
    vendor: Pachyderm
    homepage: https://www.pachyderm.com/
    maintainer: nitin@pachyderm.com
    description: "Reproducible data science"
    formats:
      - deb
    bindir: /usr/bin
