# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

project_name: pachctl
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  -
    id: pachctl
    dir: src/server/cmd/pachctl
    main: main.go
    binary: pachctl
    ldflags:
      - -X github.com/pachyderm/pachyderm/src/client/version.AdditionalVersion={{.Env.VERSION_ADDITIONAL}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
      # - -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    #gobinary: "go1.13.8"
archives:
  -
    id: pachctl-archives
    format_overrides:
      - goos: darwin
        format: zip
    wrap_in_directory: true
    files:
      - pachctl*/pachctl
checksum:
  disable: true
snapshot:
  name_template: "{{ .Env.VERSION }}{{ .Env.VERSION_ADDITIONAL }}"
changelog:
  skip: true
scoop:
  url_template: "http://github.com/pachyderm/pachyderm/releases/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: pachyderm
    name: pachctl
  commit_author:
    name: nitin
    email: nitin@pachyderm.com
  commit_msg_template: "Update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://www.pachyderm.com/"
  description: "Reproducible data science"
nfpms:
  -
    id: pachctl-deb
    package_name: pachctl
    file_name_template: "{{ .ProjectName }}_{{ .Env.VERSION }}{{ .Env.VERSION_ADDITIONAL }}_{{ .Arch }}"
    builds: 
      - pachctl
    replacements:
      linux: ""
      amd64: amd64
    vendor: Pachyderm
    homepage: https://www.pachyderm.com/
    maintainer: nitin@pachyderm.com
    description: "Reproducible data science"
    formats:
      - deb
    bindir: /usr/bin
release:
  ids:
    - pachctl-archives
    - pachctl-deb
  prerelease: auto
  disable: true
