project_name: pachctl

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  -
    id: pachctl
    dir: src/server/cmd/pachctl
    main: main.go
    binary: pachctl
    ldflags:
      - -X github.com/pachyderm/pachyderm/src/client/version.AdditionalVersion={{.Env.VERSION_ADDITIONAL}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    gcflags:
      - all=-trimpath={{.Env.TRIMPATH}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  -
    id: pachctl-archives
    format_overrides:
      - goos: darwin
        format: zip
    wrap_in_directory: true
    files:
      - pachctl*/pachctl

checksum:
  disable: true

snapshot:
  name_template: "{{ .Env.VERSION }}{{ .Env.VERSION_ADDITIONAL }}"

changelog:
  skip: true

nfpms:
  -
    id: pachctl-deb
    package_name: pachctl
    file_name_template: "{{ .ProjectName }}_{{ .Env.VERSION }}{{ .Env.VERSION_ADDITIONAL }}_{{ .Arch }}"
    builds: 
      - pachctl
    replacements:
      linux: ""
      amd64: amd64
    vendor: Pachyderm
    homepage: https://www.pachyderm.com/
    maintainer: nitin@pachyderm.com
    description: "Reproducible data science"
    formats:
      - deb
    bindir: /usr/bin

release:
  prerelease: auto
