dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.6
branches:
  except:
    - /^v[0-9]/
before_install:
- echo 'DOCKER_OPTS="-H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker
  > /dev/null
before_script:
- wget https://storage.googleapis.com/kubernetes-release/release/v1.2.0/bin/linux/amd64/kubectl
- chmod +x kubectl
- sudo mv kubectl /usr/local/bin/
- make launch-kube
- kubectl get all
- docker version
script:
- make test-fuse
after_success:
- make release
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
