dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.8
branches:
  except:
    - /^v[0-9]/
before_install:
- echo 'DOCKER_OPTS="-H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker
  > /dev/null
- sudo apt-get install -qq pkg-config fuse
- sudo modprobe fuse
- sudo chmod 666 /dev/fuse
- sudo cp etc/build/fuse.conf /etc/fuse.conf
- sudo chown root:$USER /etc/fuse.conf
- sudo mkdir -p /var/lib/kubelet
- sudo mount -o bind /var/lib/kubelet /var/lib/kubelet
- sudo mount --make-shared /var/lib/kubelet
# Decrypt gke credentials used by batch tests
- openssl aes-256-cbc -K $encrypted_08b2466633b4_key -iv $encrypted_08b2466633b4_iv -in ./etc/testing/travis-batch-test-b2543bf99978.json.enc -out ./etc/testing/travis-batch-test-b2543bf99978.json -d

before_script:
- wget https://storage.googleapis.com/kubernetes-release/release/v1.6.2/bin/linux/amd64/kubectl
- chmod +x kubectl
- sudo mv kubectl /usr/local/bin/
- make launch-kube
- kubectl get all
- docker version

# Install any deps used by our "batch test" cron
- ./etc/testing/travis_install_batch_deps.sh
script:
- make lint
- travis_wait 30 ./etc/testing/travis.sh
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
