dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.9
branches:
  except:
    - /^v[0-9]/
before_install:
- sudo etc/testing/ci/before_install.sh
before_script:
- etc/testing/ci/launch_k8s.sh
- docker version
# Install any deps used by our "batch test" cron
- ./etc/testing/ci/travis_install_batch_deps.sh
script:
- docker images | wc -l
- docker images
- sudo df -k /
- sudo du -h / -d 5 | sort -h | tail -n 20
- make lint vet
- ./etc/testing/travis.sh
after_failure:
- kubectl get all
- kubectl describe pod -l app=pachd
- kubectl get pod | grep pipeline | cut -f 1 -d " " | while read pod; do kubectl describe po/$pod; kubectl logs op/$pod user; kubectl logs po/$pod storage; done
- kubectl describe node/127.0.0.1
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
  email:
    recipients:
      - derek@pachyderm.io
    on_success: never
    on_failure: always
