sudo: required
services:
  - docker
language: go
go:
  - 1.6
branches:
  only:
    - ci_debug
before_script:
  - wget https://storage.googleapis.com/kubernetes-release/release/v1.0.1/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/
  - sudo docker-machine ssh dev -fTNL 8080:localhost:8080 -L 30650:localhost:30650
  - kubectl get all
  - docker version
script:
  - make test
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
