dist: trusty
sudo: required
services:
- docker
cache:
  directories:
    - /home/travis/.cache/go-build
    - $HOME/docker
# bump to test cache. Bump again!!!
language: go
go:
- 1.10beta1
branches:
  except:
    - /^v[0-9]/
before_cache:
# Pack up the docker builds and put em in the cached dir
-  mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
# Reload cached docker images
- if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
- sudo etc/testing/ci/before_install.sh
before_script:
- make launch-kube
- docker version
# Install any deps used by our "batch test" cron
- etc/testing/ci/travis_install_batch_deps.sh
script:
- make -j2 lint vet
- etc/testing/travis.sh
after_failure:
- kubectl version
- kubectl get all
- kubectl describe pod -l app=pachd
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
