rethink:
  image: rethinkdb:2.0.4
btrfs:
  build: etc/btrfs
  privileged: true
test:
  build: .
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - btrfs
  environment:
    - PFS_BTRFS_ROOT=/pfs/btrfs
  links:
    - rethink
  ports:
    - "6060:6060"
compile:
  build: .
  volumes:
    - _tmp:/compile
pfsd:
  build: .
  dockerfile: Dockerfile.pfsd
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - btrfs
  environment:
    - PFS_BTRFS_ROOT=/pfs/btrfs
  dockerfile: Dockerfile.pfsd
  ports:
    - "650:650"
ppsd:
  build: .
  dockerfile: Dockerfile.ppsd
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "651:651"
  links:
    - rethink
