pachyderm:
  build: .
  privileged: true
  ports:
    - "650:650"
    - "651:651"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/pfs/btrfs:/tmp/pfs/btrfs
    - _tmp:/compile
  environment:
    - PFS_BTRFS_ROOT=/tmp/pfs/btrfs/global
pfsd:
  extends:
    file: docker-compose.yml
    service: pachyderm
  dockerfile: Dockerfile.pfsd
ppsd:
  extends:
    file: docker-compose.yml
    service: pachyderm
  dockerfile: Dockerfile.ppsd
