kind: ServiceAccount
apiVersion: v1
metadata:
    name: pachyderm
    namespace: default
    labels:
        app: ""
        suite: pachyderm
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: pachyderm
    namespace: default
    labels:
        app: ""
        suite: pachyderm
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - nodes
      - pods
      - pods/log
      - endpoints
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    apiGroups:
      - ""
    resources:
      - replicationcontrollers
      - services
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - pachyderm-storage-secret
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: pachyderm
    namespace: default
    labels:
        app: ""
        suite: pachyderm
subjects:
  - kind: ServiceAccount
    name: pachyderm
    namespace: default
roleRef:
    apiGroup: ""
    kind: ClusterRole
    name: pachyderm
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: etcd
    namespace: default
    labels:
        app: etcd
        suite: pachyderm
spec:
    replicas: 1
    selector:
        matchLabels:
            app: etcd
            suite: pachyderm
    template:
        metadata:
            name: etcd
            namespace: default
            labels:
                app: etcd
                suite: pachyderm
        spec:
            volumes:
              - name: etcd-storage
                hostPath:
                    path: /var/pachyderm/etcd
                    type: DirectoryOrCreate
            containers:
              - name: etcd
                image: quay.io/coreos/etcd:v3.3.5
                command:
                  - /usr/local/bin/etcd
                  - --listen-client-urls=http://0.0.0.0:2379
                  - --advertise-client-urls=http://0.0.0.0:2379
                  - --data-dir=/var/data/etcd
                  - --auto-compaction-retention=1
                  - --max-txn-ops=10000
                  - --max-request-bytes=52428800
                  - --quota-backend-bytes=8589934592
                ports:
                  - name: client-port
                    containerPort: 2379
                  - name: peer-port
                    containerPort: 2380
                volumeMounts:
                  - name: etcd-storage
                    mountPath: /var/data/etcd
                imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
    name: etcd
    namespace: default
    labels:
        app: etcd
        suite: pachyderm
spec:
    ports:
      - name: client-port
        port: 2379
        nodePort: 32379
    selector:
        app: etcd
    type: NodePort
---
kind: Service
apiVersion: v1
metadata:
    name: pachd
    namespace: default
    labels:
        app: pachd
        suite: pachyderm
    annotations:
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
spec:
    ports:
      - name: api-grpc-port
        port: 650
        nodePort: 30650
      - name: trace-port
        port: 651
        nodePort: 30651
      - name: api-http-port
        port: 652
        nodePort: 30652
      - name: saml-port
        port: 654
        nodePort: 30654
      - name: api-git-port
        port: 999
        nodePort: 30999
      - name: s3gateway-port
        port: 600
        nodePort: 30600
    selector:
        app: pachd
    type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: pachd
    namespace: default
    labels:
        app: pachd
        suite: pachyderm
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pachd
            suite: pachyderm
    template:
        metadata:
            name: pachd
            namespace: default
            labels:
                app: pachd
                suite: pachyderm
            annotations:
                iam.amazonaws.com/role: ""
        spec:
            volumes:
              - name: pach-disk
                hostPath:
                    path: /var/pachyderm/pachd
                    type: DirectoryOrCreate
              - name: pachyderm-storage-secret
                secret:
                    secretName: pachyderm-storage-secret
            containers:
              - name: pachd
                image: pachyderm/pachd:1.9.9
                ports:
                  - name: api-grpc-port
                    containerPort: 650
                    protocol: TCP
                  - name: trace-port
                    containerPort: 651
                  - name: api-http-port
                    containerPort: 652
                    protocol: TCP
                  - name: peer-port
                    containerPort: 653
                    protocol: TCP
                  - name: api-git-port
                    containerPort: 999
                    protocol: TCP
                  - name: saml-port
                    containerPort: 654
                    protocol: TCP
                env:
                  - name: PACH_ROOT
                    value: /pach
                  - name: ETCD_PREFIX
                  - name: NUM_SHARDS
                    value: "16"
                  - name: STORAGE_BACKEND
                    value: LOCAL
                  - name: STORAGE_HOST_PATH
                    value: /var/pachyderm/pachd
                  - name: WORKER_IMAGE
                    value: pachyderm/worker:1.9.9
                  - name: IMAGE_PULL_SECRET
                  - name: WORKER_SIDECAR_IMAGE
                    value: pachyderm/pachd:1.9.9
                  - name: WORKER_IMAGE_PULL_POLICY
                    value: IfNotPresent
                  - name: PACHD_VERSION
                    value: 1.9.9
                  - name: METRICS
                    value: "true"
                  - name: LOG_LEVEL
                    value: info
                  - name: BLOCK_CACHE_BYTES
                    value: 256M
                  - name: IAM_ROLE
                  - name: NO_EXPOSE_DOCKER_SOCKET
                    value: "true"
                  - name: PACHYDERM_AUTHENTICATION_DISABLED_FOR_TESTING
                    value: "false"
                  - name: PACHD_POD_NAMESPACE
                    valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                  - name: PACHD_MEMORY_REQUEST
                    valueFrom:
                        resourceFieldRef:
                            containerName: pachd
                            resource: requests.memory
                  - name: EXPOSE_OBJECT_API
                    value: "false"
                  - name: GOOGLE_BUCKET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: google-bucket
                            optional: true
                  - name: GOOGLE_CRED
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: google-cred
                            optional: true
                  - name: MICROSOFT_CONTAINER
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: microsoft-container
                            optional: true
                  - name: MICROSOFT_ID
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: microsoft-id
                            optional: true
                  - name: MICROSOFT_SECRET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: microsoft-secret
                            optional: true
                  - name: MINIO_BUCKET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-bucket
                            optional: true
                  - name: MINIO_ENDPOINT
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-endpoint
                            optional: true
                  - name: MINIO_ID
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-id
                            optional: true
                  - name: MINIO_SECRET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-secret
                            optional: true
                  - name: MINIO_SECURE
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-secure
                            optional: true
                  - name: MINIO_SIGNATURE
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-signature
                            optional: true
                  - name: AMAZON_REGION
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-region
                            optional: true
                  - name: AMAZON_BUCKET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-bucket
                            optional: true
                  - name: AMAZON_ID
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-id
                            optional: true
                  - name: AMAZON_SECRET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-secret
                            optional: true
                  - name: AMAZON_TOKEN
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-token
                            optional: true
                  - name: AMAZON_VAULT_ADDR
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-vault-addr
                            optional: true
                  - name: AMAZON_VAULT_ROLE
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-vault-role
                            optional: true
                  - name: AMAZON_VAULT_TOKEN
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-vault-token
                            optional: true
                  - name: AMAZON_DISTRIBUTION
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-distribution
                            optional: true
                  - name: CUSTOM_ENDPOINT
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: custom-endpoint
                            optional: true
                  - name: RETRIES
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: retries
                            optional: true
                  - name: TIMEOUT
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: timeout
                            optional: true
                  - name: UPLOAD_ACL
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: upload-acl
                            optional: true
                  - name: REVERSE
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: reverse
                            optional: true
                  - name: PART_SIZE
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: part-size
                            optional: true
                  - name: MAX_UPLOAD_PARTS
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: max-upload-parts
                            optional: true
                volumeMounts:
                  - name: pach-disk
                    mountPath: /pach
                  - name: pachyderm-storage-secret
                    mountPath: /pachyderm-storage-secret
                readinessProbe:
                    exec:
                        command:
                          - /pachd
                          - --readiness
                imagePullPolicy: IfNotPresent
            serviceAccountName: pachyderm
---
kind: Secret
apiVersion: v1
metadata:
    name: pachyderm-storage-secret
    namespace: default
    labels:
        app: pachyderm-storage-secret
        suite: pachyderm
---
