apiVersion: v1
kind: Pod
metadata:
    name: split-loadtest-supervisor
    labels:
        app: split-loadtest-supervisor
spec:
    containers:
        - name: supervisor
          image: pachyderm/split-loadtest-supervisor:latest
          command:
              - /supervisor
              - --record-size=1000
              - --records-per-file=1000000
              - --files-per-commit=2
              - --num-commits=1
              - --unique-keys-per-file=2
              - --total-unique-keys=2
              - --pipeline-concurrency=1
              - --hashtree-shards=1
              - --put-file-concurrency=1
          imagePullPolicy: Always
    restartPolicy: Never
    # toleration is added in case we want a dedicated, high-memory node
    tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "loadtest"
          effect: "NoSchedule"
