apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: pachyderm-router
  name: pachyderm-router
spec:
  replicas: 1
  selector:
    name: pachyderm-router
  template:
    metadata:
      labels:
        name: pachyderm-router
    spec:
      containers:
        - name: pachyderm-router
          image: pachyderm/router
          command: ["/bin/router", "8" ]
          ports:
          - containerPort: 80
            name: port
      restartPolicy: Always
