apiVersion: v1
kind: Pod
metadata:
  name: pachyderm-test
spec:
  containers:
  - name: pachyderm-test
    image: pachyderm/test
    command: ["go",  "test", "."]
    imagePullPolicy: Always
  restartPolicy: Never
