# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  build:
    docker:
    - image: circleci/golang:1.12

    environment:
      GOPROXY: https://proxy.golang.org
      RUN_BAD_TESTS: "TRUE"

    resource_class: large

    steps:
      - checkout

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Run tests
          command: |
            ./etc/testing/examples.sh
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"            

workflows:
  version: 2 
  build-workflow:
    jobs:
      - build
