version: 2.1

orbs:
  go: circleci/go@1.6.0

jobs:
  test:
    parameters:
      bucket:
        type: string
    resource_class: large
    machine:
      image: ubuntu-2004:202101-01
    environment:
      PPS_BUCKETS: "6"
      GOPROXY: https://proxy.golang.org
      BUCKET: << parameters.bucket >>
      BIGQUERY_PROJECT: alysha-dev-006
      BIGQUERY_DATASET: pach_test
      BIGQUERY_TABLE: test_runs
      TEST_RESULTS_BUCKET: pach-test-data
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - restore_cache:
         keys:
         - pach-build-dependencies-{{ checksum "etc/testing/circle/install.sh" }}
         - pach-build-dependencies-
      - run: etc/testing/circle/install.sh 
      - save_cache:
         key: pach-build-dependencies-{{ checksum "etc/testing/circle/install.sh" }}
         paths:
         - cached-deps/
      - run: etc/kube/start-minikube.sh 
      - run: etc/testing/circle/build.sh 
      - run: etc/testing/circle/launch.sh 
      - run: etc/testing/circle/run_tests.sh 

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              bucket:
              - MISC
              # If you want to update the number of PPS buckets, you'll neet to
              # update the value of PPS_BUCKETS above
              - ADMIN
              - AUTH
              - ENTERPRISE
              - PFS
              - PPS1
              - PPS2
              - PPS3
              - PPS4
              - PPS5
              - PPS6
              - EXAMPLES
              - OBJECT
