# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # specify the version
      - image:  circleci/golang:1.12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: jumanjiman/etcd:3.3.12-r0_20190420T2025_git_214166f 11 MB
        name: etcd

    steps:
      - checkout

      - run:
          name: Waiting for etcd to be ready
          command: |
            for i in `seq 1 10`;
            do
              curl --output /dev/null --silent --head --fail http://localhost:2379/health && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Etcd && exit 1
