---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dash
    suite: pachyderm
  name: dash
spec:
  ports:
  - name: dash-http
    nodePort: 30080
    port: 8080
    targetPort: 0
  - name: grpc-proxy-http
    nodePort: 30081
    port: 8081
    targetPort: 0
  selector:
    app: dash
    suite: pachyderm
  type: NodePort
status:
  loadBalancer: {}
