{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pg-bouncer
    suite: pachyderm
  name: pg-bouncer
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: client-port
    nodePort: 30229
    port: 5432
  selector:
    app: pg-bouncer
    suite: pachyderm
  type: NodePort
{{- end }}
