apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pg-bouncer
    suite: pachyderm
  name: pg-bouncer
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: client-port
    nodePort: 32228
    port: 5432
    targetPort: 0
  selector:
    app: pg-bouncer
  type: {{ .Values.pgbouncer.service.type }}
