site_name: Pachyderm Documentation
site_description: Pachyderm Documention
site_author: Pachyderm Team
site_url: https://docs.pachyderm.io

repo_name: pachyderm/pachyderm
repo_url: https://github.com/pachyderm/pachyderm
edit_uri: ""

# Copyright
copyright: 'Copyright Pachyderm Inc, 2019'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html
  include_search_page: true
  search_index_only: true
  language: en
  feature:
    tabs: true
  palette:
    primary: #4D5A7E
    accent: #4D5A7E
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/pachyderm/pachyderm
    - type: twitter
      link: https://twitter.com/pachydermio
    - type: linkedin
      link: https://www.linkedin.com/company/pachyderm-inc-

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - mdx_truly_sane_lists:
      nested_indent: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
    - Home: index.md
    - Getting Started:
        - getting_started/local_installation.md
        - getting_started/beginner_tutorial.md
    - Concepts:
        - Versioned Data Concepts:
            - Overview: concepts/data-concepts/index.md
            - Repository: concepts/data-concepts/repo.md
            - Commit: concepts/data-concepts/commit.md
            - Branch: concepts/data-concepts/branch.md
            - File: concepts/data-concepts/file.md
            - Provenance: concepts/data-concepts/provenance.md
        - Pipeline Concepts:
            - Overview: concepts/pipeline-concepts/index.md
            - Pipeline:
                - Overview: concepts/pipeline-concepts/pipeline/index.md
                - Cross and Union: concepts/pipeline-concepts/pipeline/cross-union.md
                - Cron: concepts/pipeline-concepts/pipeline/cron.md
            - Job: concepts/pipeline-concepts/job.md
            - Datum:
                - Overview: concepts/pipeline-concepts/datum/index.md
                - Glob Patterns: concepts/pipeline-concepts/datum/glob-pattern.md
                - Datum Processing: concepts/pipeline-concepts/datum/relationship-between-datums.md
            - Service: concepts/pipeline-concepts/service.md
            - Spout: concepts/pipeline-concepts/spout.md
    - How-Tos:
        - Individual Developer Workflow: how-tos/individual-developer-workflow.md
        - Team Developer Workflow: how-tos/team-developer-workflow.md
        - Load Your Data Into Pachyderm: how-tos/load-data-into-pachyderm.md
        - Export Your Data From Pachyderm: how-tos/export-data-out-pachyderm.md
        - Split Data:
            - Overview: how-tos/splitting-data/index.md
            - Splitting Data for Distributed Processing: how-tos/splitting-data/splitting.md
            - Adjusting Data Processing by Splitting Data: how-tos/splitting-data/adjusting_data_processing_w_split.md
        - Combine, Merge, and Join Data: how-tos/combining.md
        - Create a Machine Learning Workflow: how-tos/create-ml-workflow.md
        - Run a Pipeline on a Specific Commit: how-tos/run_pipeline.md
        - Update a Pipeline: how-tos/updating_pipelines.md
        - Processing Time-Windowed Data: how-tos/time_windows.md
        - Delete Data: how-tos/removing_data_from_pachyderm.md
        - Configure Distributed Computing: how-tos/distributed_computing.md
        - Deferred Processing of Data: how-tos/deferred_processing.md
        - Ingress and Egress Data from an External Object Store: how-tos/ingressing_from_diff_cloud.md
    - Deploy and Manage:
        - Deploy Pachyderm:
            - Deploy on GKE: deploy-manage/deploy/google_cloud_platform.md
            - Deploy on AWS:
                - Overview: deploy-manage/deploy/amazon_web_services/index.md
                - Deploy Pachyderm on Amazon EKS: deploy-manage/deploy/amazon_web_services/deploy-eks.md
                - Deploy Kubernetes with kops: deploy-manage/deploy/amazon_web_services/aws-deploy-kubernetes-kops.md
                - Deploy Pachyderm on AWS: deploy-manage/deploy/amazon_web_services/aws-deploy-pachyderm.md
                - Deploy a Pachyderm Cluster with CloudFront: deploy-manage/deploy/amazon_web_services/aws_cloudfront.md
            - Deploy on Azure: deploy-manage/deploy/azure.md
            - Deploy on OpenShift: deploy-manage/deploy/openshift.md
            - Deploy On-Premises: deploy-manage/deploy/on_premises.md
            - Create a Custom Deployment:
                - Overview: deploy-manage/deploy/deploy_custom/index.md
                - Before You Begin: deploy-manage/deploy/deploy_custom/deploy_custom_before_you_begin.md
                - Pachyderm Deployment Manifest: deploy-manage/deploy/deploy_custom/deploy_custom_pachyderm_deployment_manifest.md
                - Configuring Persistent Disk Parameters: deploy-manage/deploy/deploy_custom/deploy_custom_configuring_persistent_disk_parameters.md
                - Configuring Object Store: deploy-manage/deploy/deploy_custom/deploy_custom_configuring_object_store.md
                - Create a Complete Configuration: deploy-manage/deploy/deploy_custom/deploy_custom_complete_example_invocation.md
                - Additional flags: deploy-manage/deploy/deploy_custom/deploy_custom_additional_flags.md
                - Other Customizations:
                    - Deploy in a Custom Namespace: deploy-manage/deploy/namespaces.md
                    - Deploy a Custom Object Store: deploy-manage/deploy/non-cloud-object-stores.md
                    - Configure RBAC: deploy-manage/deploy/rbac.md
            - Configure Tracing with Jaeger: deploy-manage/deploy/tracing.md
            - Connect to a Pachyderm cluster: deploy-manage/deploy/connect-to-cluster.md
        - Manage Pachyderm:
            - Manage Cluster Access: deploy-manage/manage/cluster-access.md
            - Autoscale your Cluster: deploy-manage/manage/autoscaling.md
            - Batching Pachyderm with Transactions: deploy-manage/manage/batching_pachyderm_with_transactions.md
            - Backup and Restore: deploy-manage/manage/backup_restore.md
            - Storage Use Optimization: deploy-manage/manage/data_management.md
            - Use GPUs: deploy-manage/manage/gpus.md
            - Sharing GPU Resources: deploy-manage/manage/sharing_gpu_resources.md
            - Migrate to a Major Version: deploy-manage/manage/migrations.md
            - Upgrade your Cluster: deploy-manage/manage/upgrades.md
            - Disable Usage Metrics: deploy-manage/manage/disable-metrics.md
    - Reference:
        - Pipeline Specification: reference/pipeline_spec.md
        - Pachyderm Config Specification: reference/config_spec.md
        - Pachyderm Language Clients: reference/clients.md
        - S3 Gateway API Reference: reference/s3gateway_api.md
        - Pachctl Reference: reference/pachctl/index.md
        - Examples: examples/examples.md
    - Enterprise:
        - Overview: enterprise/overview.md
        - Deploy Enterprise Edition: enterprise/deployment.md
        - Configure Access Controls: enterprise/auth/auth.md
        - Advanced Statistics: enterprise/stats.md
        - Using the S3 Gateway: enterprise/s3gateway.md
    - Troubleshooting:
        - General Troubleshooting: troubleshooting/general_troubleshooting.md
        - Deployment Troubleshootin: troubleshooting/deploy_troubleshooting.md
        - Pipeline Troubleshooting: troubleshooting/pipeline_troubleshooting.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - autosite_name: Pachyderm Documentation
