site_name: Pachyderm Documentation
site_description: Pachyderm Documention
site_author: Pachyderm Team
site_url: https://docs.pachyderm.io

repo_name: pachyderm/pachyderm
repo_url: https://github.com/pachyderm/pachyderm
edit_uri: ""

# Copyright
copyright: 'Copyright Pachyderm Inc, 2019'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html
  include_search_page: true
  search_index_only: true
  language: en
  feature:
    tabs: true
  palette:
    primary: #4D5A7E
    accent: #4D5A7E
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/pachyderm/pachyderm
    - type: twitter
      link: https://twitter.com/pachydermio
    - type: linkedin
      link: https://www.linkedin.com/company/pachyderm-inc-

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown_include.include:
      base_path: docs
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
    - Home: index.md
    - Getting Started:
        - Welcome: getting-started/index.md
        - Install Pachyderm Locally: getting-started/local_installation.md
        - Beginner Tutorial: getting-started/beginner_tutorial.md
    - Concepts:
        - Versioned Data Concepts:
            - Overview: concepts/data-concepts/index.md
            - Repository: concepts/data-concepts/repo.md
            - Commit: concepts/data-concepts/commit.md
            - Branch: concepts/data-concepts/branch.md
            - File: concepts/data-concepts/file.md
            - Provenance: concepts/data-concepts/provenance.md
        - Pipeline Concepts:
            - Overview: concepts/pipeline-concepts/index.md
            - Pipeline:
                - Overview: concepts/pipeline-concepts/pipeline/index.md
                - Cross and Union: concepts/pipeline-concepts/pipeline/cross-union.md
                - Cron: concepts/pipeline-concepts/pipeline/cron.md
            - Job: concepts/pipeline-concepts/job.md
            - Datum:
                - Overview: concepts/pipeline-concepts/datum/index.md
                - Glob Patterns: concepts/pipeline-concepts/datum/glob-pattern.md
                - Datum Processing: concepts/pipeline-concepts/datum/relationship-between-datums.md
            - Service: concepts/pipeline-concepts/service.md
            - Spout: concepts/pipeline-concepts/spout.md
    - How-Tos:
        - Getting Your Data into Pachyderm: cookbook/getting_data_into_pachyderm.md
        - Getting Your Data out of Pachyderm: cookbook/getting_data_out_of_pachyderm.md
        - Creating Analysis Pipelines: cookbook/creating_analysis_pipelines.md
    - Admin:
        - Overview: admin/index.md
        - Autoscale your Cluster: admin/autoscaling.md
        - Backup and Restore: admin/backup_restore.md
        - Manage your Data: admin/data_management.md
        - Sharing GPU Resources: admin/sharing_gpu_resources.md
        - Migrate to a Major Version: admin/migrations.md
        - Upgrade your Cluster: admin/upgrades.md
    - Reference:
        - Pipeline Specification: reference/pipeline_spec.md
        - Pachyderm Config Specification: reference/config_spec.md
        - Pachyderm Language Clients: reference/clients.md
        - S3 Gateway API Reference: reference/s3gateway_api.md
        - Pachctl Reference: reference/pachctl/index.md
    - Enterprise:
        - Overview: enterprise/overview.md
        - Deploy Enterprise Edition: enterprise/deployment.md
        - Configure Access Controls: enterprise/auth.md
        - Advanced Statistics: enterprise/stats.md
        - Using the S3 Gateway: enterprise/s3gateway.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - autosite_name: Pachyderm Documentation
