[build]
  base = "doc/"
  command = "./build.sh"
  publish = "site/"
  ignore = "git diff --quiet HEAD^ HEAD -- ."

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]

  entryPoints = [
    "latest/index.html",
  ]
 
  recursive = true
  pretty = true
 
  # You can mark some check as skipped, which will block checklinks
  # from ever attempting to execute them.
  # skipPatterns is an array of strings you can match against failing reports
  skipPatterns = ["404.html"]
 
  # You can mark some check as todo, which will execute the check, but allow failures.
  # todoPatterns is an array of strings you can match against failing reports
  todoPatterns = []

  checkExternal = false
  followSourceMaps = false

[[redirects]]
  from = "/"
  to = "/latest/"
  status = 301
  force = true

[[redirects]]
  from = "/en/latest/index.html"
  to = "/latest/"
  status = 301
  force = true

[[redirects]]
  from = "/en/latest/*"
  to = "/latest/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/archive/*"
  to = "/latest/archive/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.pachyderm.io/*"
  to = "https://docs.pachyderm.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/getting_started/*"
  to = "/latest/getting_started/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/concepts/*"
  to = "/latest/concepts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/how-tos/use-jupyterhub/"
  to = "/latest/how-tos/use-pachyderm-ide/"
  status = 301
  force = true

[[redirects]]
  from = "/how-tos/use-jupyterhub/using-jupyterhub/"
  to = "/latest/how-tos/use-pachyderm-ide/using-pachyderm-ide/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/use-jupyterhub/"
  to = "/latest/how-tos/use-pachyderm-ide/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/use-jupyterhub/using-jupyterhub/"
  to = "/latest/how-tos/use-pachyderm-ide/using-pachyderm-ide/"
  status = 301
  force = true

[[redirects]]
  from = "/how-tos/distributed_computing/"
  to = "/latest/concepts/pipeline-concepts/distributed_computing/"
  status = 301
  force = true

[[redirects]]
  from = "/how-tos/deferred_processing/"
  to = "/latest/concepts/advanced-concepts/deferred_processing/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/distributed_computing/"
  to = "/latest/concepts/advanced-concepts/distributed_computing/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/deferred_processing/"
  to = "/latest/concepts/advanced-concepts/deferred_processing/"
  status = 301
  force = true

[[redirects]]
  from = "/how-tos/*"
  to = "/latest/how-tos/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/hub/hub_getting_started/"
  to = "/latest/hub/hub_getting_started/"
  status = 301
  force = true

[[redirects]]
  from = "/deploy-manage/deploy/deploy-pachyderm-jupyterhub/"
  to = "/latest/deploy-manage/deploy/deploy-pachyderm-ide/"
  status = 301
  force = true

[[redirects]]
  from = "/deploy-manage/deploy/migrations/"
  to = "/latest/deploy-manage/manage/migrations/"
  status = 301
  force = true

[[redirects]]
  from = "/deploy-manage/*"
  to = "/latest/deploy-manage/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/reference/*"
  to = "/latest/reference/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/latest/enterprise/saml/"
  to = "/latest/enterprise/auth/saml/saml/"
  status = 301
  force = true

[[redirects]]
  from = "/enterprise/"
  to = "/latest/enterprise/overview/"
  status = 301
  force = true

[[redirects]]
  from = "/enterprise/*"
  to = "/latest/enterprise/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/troubleshooting/*"
  to = "/latest/troubleshooting/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/contributing/*"
  to = "/latest/contributing/:splat"
  status = 301
  force = true









