{{ if eq .Values.pachd.storage.backend "GOOGLE" }}
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: etcd
    suite: pachyderm
  name: etcd-storage-class
parameters:
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
{{ end }}
