apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  generateName: mnist-pach-s3-gateway-example
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: ysimonson/pach_kflow_example:v3.1.5
            command:
              - "python3"
              - "/app/tfjob.py"
            env:
              - name: S3_ENDPOINT
                value: "pachd.kubeflow:600"
              - name: S3_USE_HTTPS
                value: "0"
              - name: S3_VERIFY_SSL
                value: "0"
              - name: S3_REQUEST_TIMEOUT_MSEC
                value: "600000"
              - name: S3_CONNECT_TIMEOUT_MSEC
                value: "600000"
              - name: S3_REGION
                value: "us-east1-b"
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: ysimonson/pach_kflow_example:v3.1.5
            command:
              - "python3"
              - "/app/tfjob.py"
            env:
              - name: S3_ENDPOINT
                value: "pachd.kubeflow:600"
              - name: S3_USE_HTTPS
                value: "0"
              - name: S3_VERIFY_SSL
                value: "0"
              - name: S3_REQUEST_TIMEOUT_MSEC
                value: "600000"
              - name: S3_CONNECT_TIMEOUT_MSEC
                value: "600000"
              - name: S3_REGION
                value: "us-east1-b"
