apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres
    suite: pachyderm
  name: postgres-headless
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: client-port
    port: 5432
    targetPort: 0
  selector:
    app: postgres
status:
  loadBalancer: {}
