apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres
    suite: pachyderm
  name: postgres
  namespace: default
spec:
  ports:
  - name: client-port
    port: 5432
    targetPort: 0
  selector:
    app: postgres
  type: ClusterIP
