allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: postgres
    suite: pachyderm
  name: postgres-storage-class
parameters:
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
