{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{ if and (or (.Values.pachd.enterpriseLicenseKey) (.Values.pachd.activateEnterpriseMember)) ( or (.Release.IsInstall) (.Values.pachd.activateEnterprise)) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pachyderm-config-{{ date "20060102150405" now }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  {{- if .Values.pachd.configJob.annotations -}}
    {{ toYaml .Values.pachd.configJob.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: pachd
    suite: pachyderm
spec:
  template:
    spec:
      containers:
      - name: config-pod
        image: pachyderm/config-pod:0.5
        command: [ "/config-pod" ]
        volumeMounts:
        - name: config
          mountPath: "/pachConfig"
        env:
        {{- if .Values.console.enabled }}
        - name: CONSOLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pachyderm-console-secret
              key: OAUTH_CLIENT_SECRET
        {{- end}}
        {{- if .Values.enterpriseServer.enabled }}
        - name: PACH_ADDR
          value: "grpc://pach-enterprise:1650"
        {{- end }}
        {{- if .Values.pachd.rootTokenSecret.enabled }}    
        - name: ROOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pachd.rootTokenSecret.name }}
              key: {{ .Values.pachd.rootTokenSecret.key }}
        {{- end }}
        {{- if .Values.pachd.enterpriseRootTokenSecret.enabled }}
        - name: ENTERPRISE_ROOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pachd.enterpriseRootTokenSecret.name }}
              key: {{ .Values.pachd.enterpriseRootTokenSecret.key }}
        {{- end }}
        {{- if .Values.pachd.enterpriseSecretSecret.enabled }}
        - name: ENTERPRISE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pachd.enterpriseSecretSecret.name }}
              key: {{ .Values.pachd.enterpriseSecretSecret.key }}
        {{- end }}
        {{- if .Values.pachd.oauthClientSecretSecret.enabled }}
        - name: PACHD_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pachd.oauthClientSecretSecret.name }}
              key: {{ .Values.pachd.oauthClientSecretSecret.key }}
        {{- end }}
        envFrom:
        - secretRef:
            name: pachyderm-deployment-id-secret
      restartPolicy: Never
      volumes:
      - name: config
        secret: 
          secretName: pachyderm-bootstrap-config
  backoffLimit: 4
{{- end }}
