{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if .Values.pachd.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "1656"
    prometheus.io/scrape: "true"
  labels:
    app: pachd
    suite: pachyderm
    {{- if .Values.pachd.service.labels }}
    {{- toYaml .Values.pachd.service.labels | nindent 4 }}
    {{- end }}
  name: pachd
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: api-grpc-port
    targetPort: api-grpc-port
    port: 1650
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30650
    {{- end }}
  - name: oidc-port
    targetPort: oidc-port
    port: 1657
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30657
    {{- end }}
  - name: identity-port
    targetPort: identity-port
    port: 1658
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30658
    {{- end }}
  - name: s3gateway-port
    targetPort: s3gateway-port
    port: 1600
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30600
    {{- end }}
  - name: prom-metrics
    targetPort: prom-metrics
    port: 1656
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30656
    {{- end }}
  selector:
    app: pachd
  type: {{ .Values.pachd.service.type }}
{{- end }}
