apiVersion: v1
kind: Secret
metadata:
  name: $PIPELINE_DOCKER_SECRETS
type: Opaque
data:
  # Any secret variables should go here and they must end with _ENCODED
  # That is due to envsubst and magic required to make kubectl secrets
  DATABASE_USERNAME: $DATABASE_USERNAME_ENCODED
  DATABASE_PASSWORD: $DATABASE_PASSWORD_ENCODED
  DATABASE_HOSTNAME: $DATABASE_HOSTNAME_ENCODED
  DATABASE_PORT: $DATABASE_PORT_ENCODED
