apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "656"
    prometheus.io/scrape: "true"
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
spec:
  ports:
  - name: api-grpc-port
    nodePort: 30650
    port: 650
    targetPort: 0
  - name: trace-port
    nodePort: 30651
    port: 651
    targetPort: 0
  - name: api-http-port
    nodePort: 30652
    port: 652
    targetPort: 0
  - name: saml-port
    nodePort: 30654
    port: 654
    targetPort: 0
  - name: oidc-port
    nodePort: 30657
    port: 657
    targetPort: 0
  - name: api-git-port
    nodePort: 30655
    port: 655
    targetPort: 0
  - name: s3gateway-port
    nodePort: 30600
    port: 600
    targetPort: 0
  selector:
    app: pachd
