---
apiVersion: v1
data:
  google-bucket: YmxhaA==
  google-cred: ""
kind: Secret
metadata:
  labels:
    app: pachyderm-storage-secret
    suite: pachyderm
  name: pachyderm-storage-secret
  namespace: default
