{{ if .Values.tls.enabled }}
apiVersion: v1
data:
  tls.crt: {{ .Values.tls.crt }} #TODO Base64
  tls.key: {{ .Values.tls.key }} #TODO Base64
kind: Secret
metadata:
  labels:
    app: pachd-tls-cert
    suite: pachyderm
  name: pachd-tls-cert
{{ end }}