{{ if and .Values.tls.crt .Values.tls.key }}
apiVersion: v1
data:
  tls.crt: {{ .Values.tls.crt | b64enc}}
  tls.key: {{ .Values.tls.key | b64enc }}
kind: Secret
metadata:
  labels:
    app: pachd-tls-cert
    suite: pachyderm
  name: pachd-tls-cert
{{ end }}
