---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash
spec:
  template:
    metadata:
      name: dash
    spec:
      containers:
      - image: pachyderm/dash:1.9.0
        imagePullPolicy: IfNotPresent
        name: dash
        ports:
        - containerPort: 8080
          name: dash-http
      - image: pachyderm/grpc-proxy:0.4.10
        imagePullPolicy: IfNotPresent
        name: grpc-proxy
        ports:
        - containerPort: 8081
          name: grpc-proxy-http
